version: '3.9'
services:
  postgresql_main:
    image: postgres:latest
    container_name: society_db
    ports:
      - "5440:5432"
    networks:
      - society-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_main

  society:
    container_name: society
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_JDBC_URL=jdbc:postgresql://society_db:5432/db_main
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_PATH_TO_DRIVER_CLASS=org.postgresql.Driver
    networks:
      - society-network
    depends_on:
      - postgresql_main

networks:
  society-network:
    ipam:
      driver: default
      config:
        - subnet: "10.200.204.0/24"